/**
 * The Markdown review summary — the short document a person reads before the long JSON one.
 *
 * ── Why both artefacts exist ────────────────────────────────────────────────
 *
 * The canonical JSON manifest is complete and machine-readable, and nobody reads 100 products
 * with 1,500 facts in it by eye. This renders the same plan as a few pages: the counts that
 * have to reconcile, every conflict grouped by what it is about, and one line per product.
 *
 * ── Determinism ─────────────────────────────────────────────────────────────
 *
 * Every line here is a pure function of the plan. No clock, no absolute path, no environment,
 * no connection detail — the same reasons the manifest hash is meaningful apply to this file,
 * and the byte-identity check covers both.
 */

import type { Manifest, ManifestRow } from "./manifest";

function table(headers: readonly string[], rows: readonly (readonly string[])[]): string[] {
  const lines = [`| ${headers.join(" | ")} |`, `| ${headers.map(() => "---").join(" | ")} |`];
  for (const row of rows) lines.push(`| ${row.join(" | ")} |`);
  return lines;
}

function conflictCodes(row: ManifestRow): string {
  const codes = [
    ...new Set(row.flags.filter((flag) => flag.severity === "conflict").map((flag) => flag.code)),
  ].sort();
  return codes.length === 0 ? "—" : codes.join(", ");
}

export function renderReviewSummary(manifest: Manifest): string {
  const counts = manifest.counts;
  const technical = counts.technical;
  const integrity = manifest.documentIntegrity;
  const lines: string[] = [];

  lines.push("# Catalog import — dry-run review summary");
  lines.push("");
  lines.push(
    "Generated by the importer. Nothing in this run was written to any database, nothing " +
      "was approved, and no identity was ratified.",
  );
  lines.push("");

  lines.push("## Run");
  lines.push("");
  lines.push(
    ...table(
      ["Field", "Value"],
      [
        ["Importer", manifest.importerVersion],
        ["Workbook", manifest.workbook.fileName],
        ["Workbook provenance", manifest.workbook.provenance],
        ["Workbook SHA-256", manifest.workbook.sha256],
        ["Workbook bytes", String(manifest.workbook.byteSize)],
        ["Worksheet", manifest.workbook.sheetName],
        ["Manifest SHA-256", manifest.manifestHash],
      ],
    ),
  );
  lines.push("");

  lines.push("## Identity");
  lines.push("");
  lines.push(
    ...table(
      ["Field", "Value"],
      [
        ["Ledger ratifiable as it stands", manifest.identityRatifiable ? "yes" : "**no**"],
        [
          "Unmatched ledger entries (never deleted)",
          String(manifest.unmatchedLedgerEntries.length),
        ],
        ["Duplicate identities", String(counts.duplicateIdentity)],
      ],
    ),
  );
  lines.push("");
  lines.push(
    ...table(
      ["Identity state", "Products"],
      [...new Set(manifest.rows.map((row) => row.identityState))]
        .sort()
        .map((state) => [
          state,
          String(manifest.rows.filter((row) => row.identityState === state).length),
        ]),
    ),
  );
  lines.push("");

  lines.push("## Product row actions");
  lines.push("");
  lines.push(
    "These are actions for the **Product row itself**. A withheld specification or an " +
      "unmapped property does not appear here — see the per-category conflicts below.",
  );
  lines.push("");
  lines.push(
    ...table(
      ["Action", "Products"],
      [
        ["INSERT", String(counts.products.insert)],
        ["UPDATE", String(counts.products.update)],
        ["SKIP", String(counts.products.skip)],
        ["CONFLICT (row blocked)", String(counts.products.conflict)],
        ["Total", String(counts.rowsParsed)],
      ],
    ),
  );
  lines.push("");

  lines.push("## Conflicts by category");
  lines.push("");
  lines.push("Products carrying at least one conflict of each kind. A row may appear in several.");
  lines.push("");
  lines.push(
    ...table(
      ["Category", "Products", "Blocks the Product row"],
      Object.entries(counts.conflictsByCategory).map(([category, count]) => [
        category,
        String(count),
        ["IDENTITY", "SLUG", "TAXONOMY"].includes(category) ? "yes" : "no",
      ]),
    ),
  );
  lines.push("");

  lines.push("## Technical facts versus Specifications");
  lines.push("");
  lines.push(
    "Every extracted reading becomes a `source_facts` row. Only a reading whose property " +
      "resolves to an approved dictionary key AND whose value satisfies the `specifications` " +
      "CHECK constraints becomes a `specifications` row.",
  );
  lines.push("");
  lines.push(
    ...table(
      ["Measure", "Count"],
      [
        ["Raw technical SourceFacts", String(technical.rawTechnicalFacts)],
        ["HIGH-confidence mapped", String(technical.highConfidenceMapped)],
        ["Unmapped / below HIGH confidence", String(technical.unmappedOrLowConfidence)],
        ["Valid Specification candidates", String(technical.validSpecificationCandidates)],
        ["— Product-level", String(technical.productLevelCandidates)],
        ["— Grade-level", String(technical.gradeLevelCandidates)],
        ["Withheld from Specification", String(technical.withheldFromSpecification)],
        ["— no approved property reference", String(technical.missingPropertyReference)],
        ["— no database-valid value shape", String(technical.invalidValueShape)],
        ["Distinct raw labels in conflict", String(technical.conflictingRawLabels)],
        ["Facts under those labels", String(technical.factsUnderConflictingRawLabels)],
        ["ProductClaim candidates", String(counts.claims)],
        ["ProductGrade candidates", String(counts.gradeRecords)],
        ["Distinct SourceFact rows", String(counts.sourceFacts)],
        ["specification_evidence links", String(counts.specificationEvidenceLinks)],
        ["claim_evidence links", String(counts.claimEvidenceLinks)],
      ],
    ),
  );
  lines.push("");

  lines.push("## Documents");
  lines.push("");
  lines.push(
    "A `source_documents` row is planned only when a planned SourceFact cites it, or when it " +
      "is the workbook the run itself was made from. A URL the workbook states and no " +
      "evidence cites is provenance, listed further down, and is never written.",
  );
  lines.push("");
  lines.push(
    ...table(
      ["Publisher", "Role", "Locator type", "Documents"],
      integrity.countsByRole.map((entry) => [
        entry.publisher,
        entry.role,
        entry.locatorType,
        String(entry.count),
      ]),
    ),
  );
  lines.push("");
  lines.push(
    ...table(
      ["Measure", "Count"],
      [
        ["Planned SourceDocument rows", String(integrity.totalDocuments)],
        ...integrity.retentionByBasis.map((entry) => [
          `— retained because ${entry.basis}`,
          String(entry.count),
        ]),
        ["Candidates addressed by the sources", String(integrity.candidateDocuments)],
        ["Provenance locators (never written)", String(integrity.provenanceLocators)],
        ["Unique locators", String(integrity.uniqueLocators)],
        ["Duplicate locators", String(integrity.duplicateLocators.length)],
        ["Captured (would carry a SourceAsset)", String(integrity.capturedDocuments)],
        ["Locator only (no stored bytes)", String(integrity.locatorOnlyDocuments)],
        ["SourceAsset rows", String(integrity.sourceAssets)],
        ["Documents with zero evidence", String(integrity.documentsWithZeroEvidence.length)],
        ["Evidence citing no planned document", String(integrity.evidenceWithoutDocument.length)],
        ["Claims citing a TDS", String(integrity.claimsCitingTechnicalDataSheet.length)],
        [
          "Readings citing a product page",
          String(integrity.technicalFactsCitingProductPage.length),
        ],
        ["Locator mismatches vs the workbook", String(counts.sourceRetrievalMismatch)],
      ],
    ),
  );
  lines.push("");

  if (manifest.provenanceLocators.length > 0) {
    lines.push("## Provenance locators — addressed, cited by nothing, NOT planned");
    lines.push("");
    lines.push(
      "These addresses stay in this manifest as workbook provenance. No SourceFact, claim or " +
        "evidence link cites them, so no `source_documents` row is planned for any of them. " +
        "The key column is the row each would occupy if its content is ever transcribed.",
    );
    lines.push("");
    lines.push(
      ...table(
        ["Would-be key", "Workbook row", "Publisher", "Role", "Locator"],
        manifest.provenanceLocators.map((entry) => [
          entry.documentKey,
          entry.rowNumber === null ? "—" : String(entry.rowNumber),
          entry.publisher,
          entry.role,
          entry.locatorValue,
        ]),
      ),
    );
    lines.push("");
  }

  if (manifest.unmappedProperties.length > 0) {
    lines.push("## Unmapped raw property labels");
    lines.push("");
    lines.push(
      ...table(
        ["Raw label", "Unit", "Occurrences", "Reason"],
        manifest.unmappedProperties.map((entry) => [
          entry.rawProperty,
          entry.rawUnit ?? "—",
          String(entry.occurrences),
          entry.reason,
        ]),
      ),
    );
    lines.push("");
  }

  lines.push("## Products");
  lines.push("");
  lines.push(
    ...table(
      [
        "sourceRef",
        "Identity",
        "Row",
        "Excel name",
        "Slug",
        "Family",
        "Type",
        "Segments",
        "Grades",
        "Spec cands",
        "Withheld",
        "Claims",
        "Action",
        "Conflicts",
        "Evidence hash",
      ],
      manifest.rows.map((row) => [
        row.sourceRef,
        row.identityState,
        String(row.rowNumber),
        row.publicProductName,
        row.proposedSlug,
        row.proposedProductFamilyKey ?? "**unresolved**",
        row.proposedProductTypeKey ?? "—",
        row.proposedSegmentKeys.length === 0 ? "—" : row.proposedSegmentKeys.join(" "),
        String(row.gradeCandidates.length),
        String(row.specificationCandidateCount),
        String(row.withheldFactCount),
        String(row.claimCandidates.length),
        row.action,
        conflictCodes(row),
        row.evidenceHash.slice(0, 12),
      ]),
    ),
  );
  lines.push("");

  return `${lines.join("\n")}\n`;
}
