import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

import { PrismaPg } from "@prisma/adapter-pg";

// The generated directory has no index barrel, so the entry point is the
// client.ts inside it — not the directory itself.
import { PrismaClient } from "../apps/api/src/prisma/generated/client";

/**
 * Loads the drafted product copy from `PRODUCT_RESEARCH_REGISTER.json` into `product_copy`
 * at `source_recorded`, so a reviewer can decide on it (ADR-019 §6).
 *
 * ```
 * SAM_ALLOW_PRODUCT_COPY_LOAD=true pnpm load:product-copy
 * ```
 *
 * ── What this does NOT do, stated first because it is the point ─────────────
 *
 * It does not publish anything. Every row lands at `source_recorded`, which is the state before any
 * human decision, and `v_product_copy_public` serves only `approved` rows — so a full run changes
 * nothing a visitor can see. The register's own rule 7,
 * `publicationBlockedUntilTechnicalApproval`, stays true after this script as it was before it.
 *
 * **And every loaded row is unapprovable until someone binds evidence to it.** The drafts were
 * written from official web metadata, not from a captured `source_document`, so nothing here writes
 * a `copy_evidence` link — and `product_copy_approval_gate` refuses an approval without one. That
 * is the designed outcome, not a gap this script should paper over: a draft with no bound source is
 * reviewable and REJECTABLE, and never approvable (ADR-019 §3). Binding evidence is a separate,
 * deliberate act by someone who has the document in hand.
 *
 * ── Three guards, in this order ─────────────────────────────────────────────
 *
 * 1. **Armed explicitly.** `SAM_ALLOW_PRODUCT_COPY_LOAD=true`, the same shape the legal-content
 *    publisher and the Prisma demo seeds use.
 * 2. **Validated before the database is opened.** Every draft is parsed and checked first, so a
 *    register carrying one bad row fails without a connection being made and without half the
 *    catalogue being written.
 * 3. **Refuses to overwrite.** A product that already has copy in that locale is SKIPPED, not
 *    updated. Copy that has been through review — approved, rejected, or currently being read by
 *    someone — must not be silently replaced by a regenerated draft, and the register is
 *    regenerated by a script.
 *
 * ── What reaches the database, and what is deliberately dropped ─────────────
 *
 * `summary` and `selectionNote`, and nothing else. Register rules 6 and 12 keep every external URL
 * and provenance locator out of `product_copy` and out of any public payload, and the schema has no
 * column for one — `primaryCta`, `secondaryCta`, `official.*` and `researchStatus` are all left in
 * the file. The CTAs in particular are layout, and layout is code (`PROJECT_HANDOFF` §6.7).
 */

// Prisma 7 does not load .env automatically, and this file is also runnable outside the Prisma CLI.
// Guarded because a fresh clone has no .env yet.
if (existsSync(".env")) {
  process.loadEnvFile();
}

const REGISTER_PATH = resolve(process.cwd(), "docs/content/PRODUCT_RESEARCH_REGISTER.json");

/**
 * The markers that mean "not reviewed text", checked case-insensitively.
 *
 * The same list `legal-content.ts` refuses, for the same reason: a placeholder that reaches a
 * reviewer looks like copy, and a reviewer who approves one has approved a marker.
 */
const PLACEHOLDER_MARKERS: readonly string[] = [
  "[to confirm",
  "[estimate",
  "lorem ipsum",
  "todo",
  "tbd",
  "xxx",
  "placeholder",
];

/**
 * The research statuses whose drafts may be loaded.
 *
 * ── Why both, and why that is not a relaxation ──────────────────────────────
 *
 * This started as `official_web_verified` alone, on the belief that the 66 drafts were exactly the
 * 66 web-verified products. That was wrong, and the first run against a clone said so: the 66
 * drafts are 36 `official_web_verified` and 30 `supplied_catalogue`, while 30 web-verified products
 * carry no draft at all.
 *
 * Refusing the `supplied_catalogue` half would not have been the safer choice — it would have been
 * an arbitrary one. Register rule 4 governs where those products' facts are SOURCED (the supplied
 * catalogue, not the open web); it does not say they may not be described. Their drafts are visibly
 * written from catalogue metadata rather than from the web, which is rule 4 being followed.
 *
 * What actually protects the catalogue here is not this list. It is that neither kind can be
 * APPROVED without a captured source document bound to it — enforced by `product_copy_approval_gate`
 * in the database, on both halves identically.
 */
const LOADABLE_RESEARCH_STATUSES: readonly string[] = [
  "official_web_verified",
  "supplied_catalogue",
];

interface CopyDraft {
  readonly locale?: unknown;
  readonly summary?: unknown;
  readonly selectionNote?: unknown;
  readonly prohibitedClaimsAdded?: unknown;
}

interface RegisterEntry {
  readonly sourceRef?: unknown;
  readonly currentName?: unknown;
  readonly researchStatus?: unknown;
  readonly copyDraft?: CopyDraft | null;
}

interface Register {
  readonly products?: unknown;
}

/** One validated draft, ready to insert. Nothing beyond these four fields survives parsing. */
interface LoadableDraft {
  readonly sourceRef: string;
  readonly name: string;
  readonly locale: string;
  readonly summary: string;
  readonly selectionNote: string | null;
}

class ProductCopyLoadError extends Error {}

function text(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  return trimmed === "" ? null : trimmed;
}

function assertNoPlaceholder(value: string, where: string): void {
  const lowered = value.toLowerCase();
  for (const marker of PLACEHOLDER_MARKERS) {
    if (lowered.includes(marker)) {
      throw new ProductCopyLoadError(
        `${where} contains the placeholder marker "${marker}". Placeholders are never loaded — ` +
          `a reviewer shown one would be approving a marker.`,
      );
    }
  }
}

/**
 * Parses the register into the drafts that may be loaded, and throws on anything questionable.
 *
 * Entries with no `copyDraft` are skipped silently — 34 of the 100 products are
 * `supplied_catalogue` and carry no draft by design (register rule 4). Everything else must be
 * complete: a partially valid register is a defect, not a subset to load.
 */
export function parseRegister(source: string): LoadableDraft[] {
  let parsed: Register;
  try {
    parsed = JSON.parse(source) as Register;
  } catch (error) {
    throw new ProductCopyLoadError(
      `The register is not valid JSON: ${error instanceof Error ? error.message : String(error)}`,
    );
  }

  const products = parsed.products;
  if (!Array.isArray(products)) {
    throw new ProductCopyLoadError(`The register has no "products" array.`);
  }

  const drafts: LoadableDraft[] = [];
  const seen = new Set<string>();

  for (const [index, raw] of products.entries()) {
    const entry = raw as RegisterEntry;
    const draft = entry.copyDraft;
    if (draft === null || draft === undefined) continue;

    const where = `products[${String(index)}]`;

    const sourceRef = text(entry.sourceRef);
    if (sourceRef === null) {
      throw new ProductCopyLoadError(`${where} carries a copyDraft but no sourceRef.`);
    }

    if (
      typeof entry.researchStatus !== "string" ||
      !LOADABLE_RESEARCH_STATUSES.includes(entry.researchStatus)
    ) {
      throw new ProductCopyLoadError(
        `${where} (${sourceRef}) carries a copyDraft but its researchStatus is ` +
          `"${String(entry.researchStatus)}", which is not a status this loader recognises. ` +
          `Recognised: ${LOADABLE_RESEARCH_STATUSES.join(", ")}.`,
      );
    }

    /*
     * The register's own self-report that the draft added a claim it should not have.
     *
     * It is `false` on all 66 today. If it is ever `true`, the run fails rather than loading the
     * row for a reviewer to catch — a prohibited claim in a draft is a defect in the generator, and
     * a queue is the wrong place to discover one.
     */
    if (draft.prohibitedClaimsAdded === true) {
      throw new ProductCopyLoadError(
        `${where} (${sourceRef}) reports prohibitedClaimsAdded: true. The generator added a claim ` +
          `it should not have; fix the draft rather than loading it for review.`,
      );
    }

    const locale = text(draft.locale);
    if (locale === null) {
      throw new ProductCopyLoadError(`${where} (${sourceRef}) has a draft with no locale.`);
    }

    const summary = text(draft.summary);
    if (summary === null) {
      throw new ProductCopyLoadError(`${where} (${sourceRef}) has a draft with no summary.`);
    }
    assertNoPlaceholder(summary, `${where} (${sourceRef}) summary`);

    const selectionNote = text(draft.selectionNote);
    if (selectionNote !== null) {
      assertNoPlaceholder(selectionNote, `${where} (${sourceRef}) selectionNote`);
    }

    const key = `${sourceRef}:${locale}`;
    if (seen.has(key)) {
      throw new ProductCopyLoadError(
        `${sourceRef} carries two drafts for locale "${locale}". One product has one piece of ` +
          `copy per language.`,
      );
    }
    seen.add(key);

    drafts.push({
      sourceRef,
      name: text(entry.currentName) ?? sourceRef,
      locale,
      summary,
      selectionNote,
    });
  }

  return drafts;
}

async function main(): Promise<void> {
  if (process.env.SAM_ALLOW_PRODUCT_COPY_LOAD !== "true") {
    console.error(
      "Refusing to run: set SAM_ALLOW_PRODUCT_COPY_LOAD=true to load product copy drafts.",
    );
    process.exitCode = 1;
    return;
  }

  // Guard 2: parsed and validated before a connection exists.
  const drafts = parseRegister(readFileSync(REGISTER_PATH, "utf8"));
  console.log(`Validated ${String(drafts.length)} drafts from the register.`);

  const connectionString = process.env.DATABASE_URL;
  if (connectionString === undefined || connectionString === "") {
    throw new ProductCopyLoadError("DATABASE_URL is not set — copy .env.example to .env first.");
  }

  // Prisma 7 requires a driver adapter for a direct PostgreSQL connection.
  const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString }) });
  let inserted = 0;
  let skippedExisting = 0;
  const unmatched: string[] = [];

  try {
    const locales = await prisma.locale.findMany({ select: { code: true, isActive: true } });
    const active = new Set(locales.filter((row) => row.isActive).map((row) => row.code));

    for (const draft of drafts) {
      if (!active.has(draft.locale)) {
        throw new ProductCopyLoadError(
          `${draft.sourceRef} has a draft for locale "${draft.locale}", which is not an active ` +
            `Locale. The locale list is data, not code — activate it first, or fix the draft.`,
        );
      }

      const product = await prisma.product.findFirst({
        where: { sourceRef: draft.sourceRef },
        select: { id: true },
      });

      if (product === null) {
        unmatched.push(draft.sourceRef);
        continue;
      }

      // Guard 3: never overwrite. A regenerated draft must not replace copy someone has decided on.
      const existing = await prisma.productCopy.findUnique({
        where: { productId_locale: { productId: product.id, locale: draft.locale } },
        select: { id: true },
      });

      if (existing !== null) {
        skippedExisting += 1;
        continue;
      }

      await prisma.productCopy.create({
        data: {
          productId: product.id,
          locale: draft.locale,
          summary: draft.summary,
          selectionNote: draft.selectionNote,
        },
        select: { id: true },
      });
      inserted += 1;
    }
  } finally {
    await prisma.$disconnect();
  }

  console.log(`Inserted ${String(inserted)} drafts at source_recorded.`);
  console.log(`Skipped ${String(skippedExisting)} that already had copy in that locale.`);

  if (unmatched.length > 0) {
    console.log(
      `Skipped ${String(unmatched.length)} whose sourceRef matched no Product: ` +
        unmatched.join(", "),
    );
  }

  console.log(
    "\nNone of these can be approved yet. Each needs a captured source document bound to it " +
      "through copy_evidence before the approval gate will accept it (ADR-019 §3).",
  );
}

main().catch((error: unknown) => {
  console.error(
    error instanceof ProductCopyLoadError
      ? `ABORTED: ${error.message}`
      : `Product copy load failed: ${error instanceof Error ? error.message : String(error)}`,
  );
  process.exit(1);
});
