/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'fa' | 'ar') | ('en' | 'fa' | 'ar')[];
  globals: {
    'about-us': AboutUs;
    'customized-solutions': CustomizedSolution;
    'quality-certifications': QualityCertification;
    'contact-us': ContactUs;
  };
  globalsSelect: {
    'about-us': AboutUsSelect<false> | AboutUsSelect<true>;
    'customized-solutions': CustomizedSolutionsSelect<false> | CustomizedSolutionsSelect<true>;
    'quality-certifications': QualityCertificationsSelect<false> | QualityCertificationsSelect<true>;
    'contact-us': ContactUsSelect<false> | ContactUsSelect<true>;
  };
  locale: 'en' | 'fa' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * admin and content-manager are editorial roles. service is for the NestJS Content module only and must never be given to a person.
   */
  roles: ('admin' | 'content-manager' | 'service')[];
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Legal pages only. Bespoke company pages are Globals with their own schemas, not entries here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL segment, identical in every locale. Lowercase letters, digits and single hyphens.
   */
  slug: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  bodyHtml?: string | null;
  lastUpdatedDate?: string | null;
  /**
   * Optional. Every field falls back to the page's own content when left empty — an empty title or description is never shipped.
   */
  seo?: {
    /**
     * Falls back to the page title.
     */
    metaTitle?: string | null;
    /**
     * Falls back to the page's own content. Aim for roughly 150–160 characters.
     */
    metaDescription?: string | null;
    /**
     * Override only. Leave empty unless this page deliberately points at another URL.
     */
    canonicalUrl?: string | null;
    /**
     * Falls back to the meta title.
     */
    ogTitle?: string | null;
    /**
     * Falls back to the meta description.
     */
    ogDescription?: string | null;
    /**
     * Shown when the page is shared. 1200×630 is the platform convention. Separate from any hero image on purpose.
     */
    socialImage?: (number | null) | Media;
    twitterCardType?: ('summary' | 'summary_large_image') | null;
    /**
     * Falls back to the Open Graph title.
     */
    twitterTitle?: string | null;
    /**
     * Falls back to the Open Graph description.
     */
    twitterDescription?: string | null;
    /**
     * Falls back to the social image above.
     */
    twitterImage?: (number | null) | Media;
    /**
     * Uncheck to mark this page noindex.
     */
    robotsIndex?: boolean | null;
    /**
     * Uncheck to mark this page nofollow.
     */
    robotsFollow?: boolean | null;
    /**
     * Internal content planning. Not a ranking factor in modern search.
     */
    keywords?: string[] | null;
    /**
     * Advanced. Replaces the automatically generated JSON-LD for this page. Leave empty to use the automatic output.
     */
    structuredDataOverride?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Editorial media for Payload-owned content only. Product and blog imagery belong to the platform database, not here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describes the image for screen readers and search engines. Say what it shows, not that it is an image.
   */
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  bodyHtml?: T;
  lastUpdatedDate?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        socialImage?: T;
        twitterCardType?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        robotsIndex?: T;
        robotsFollow?: T;
        keywords?: T;
        structuredDataOverride?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The About Us page. Team functions are modelled without invented names or biographies; milestones remain unmodelled until their facts are approved.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us".
 */
export interface AboutUs {
  id: number;
  hero: {
    eyebrow?: string | null;
    /**
     * The page's H1. Required — a document with no heading is treated as unconfigured and is not served.
     */
    title: string;
    supportingText?: string | null;
    primaryCta?: {
      /**
       * Leave empty to omit this action from the page.
       */
      label?: string | null;
      route?:
        ('products' | 'customized-solutions' | 'quality-certifications' | 'contact-us' | 'request-a-quote') | null;
    };
    secondaryCta?: {
      /**
       * Leave empty to omit this action from the page.
       */
      label?: string | null;
      route?:
        ('products' | 'customized-solutions' | 'quality-certifications' | 'contact-us' | 'request-a-quote') | null;
    };
    /**
     * Optional. The section renders without a figure when this is empty.
     */
    image?: (number | null) | Media;
    /**
     * Optional caption shown under the image.
     */
    imageCaption?: string | null;
  };
  whoWeAre?: {
    heading?: string | null;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    bodyHtml?: string | null;
    positions?:
      | {
          term: string;
          note: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional. The section renders without a figure when this is empty.
     */
    image?: (number | null) | Media;
    /**
     * Optional caption shown under the image.
     */
    imageCaption?: string | null;
  };
  expertise?: {
    heading?: string | null;
    lead?: string | null;
    items?:
      | {
          name: string;
          /**
           * Optional one-sentence description.
           */
          note?: string | null;
          /**
           * Optional. Which concept this row's glyph should represent.
           */
          icon?: ('product' | 'application' | 'blend' | 'formulation' | 'documentation' | 'supply') | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * "Why Partner with SAM Group?" — the _v2 About Us sheet's six name/reason pairs. No image and no footnote link, unlike Quality & Standards below: the sheet gives this segment nothing else.
   */
  competitiveAdvantages?: {
    heading?: string | null;
    lead?: string | null;
    items?:
      | {
          name: string;
          note: string;
          /**
           * Optional. Which concept this row's glyph should represent.
           */
          icon?: ('manufacturer' | 'customization' | 'quality' | 'supply' | 'expertise' | 'partnership') | null;
          id?: string | null;
        }[]
      | null;
  };
  team?: {
    eyebrow?: string | null;
    heading?: string | null;
    lead?: string | null;
    /**
     * Describe accountable functions, not invented people. Add names and biographies only when the real roster and photography are approved.
     */
    functions?:
      | {
          name: string;
          note: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional. The section renders without a figure when this is empty.
     */
    image?: (number | null) | Media;
    /**
     * Optional caption shown under the image.
     */
    imageCaption?: string | null;
  };
  qualityStandards?: {
    heading?: string | null;
    lead?: string | null;
    items?:
      | {
          name: string;
          /**
           * Optional second line.
           */
          note?: string | null;
          id?: string | null;
        }[]
      | null;
    footnote?: string | null;
    footnoteCta?: {
      /**
       * Leave empty to omit this action from the page.
       */
      label?: string | null;
      route?:
        ('products' | 'customized-solutions' | 'quality-certifications' | 'contact-us' | 'request-a-quote') | null;
    };
    /**
     * Optional. The section renders without a figure when this is empty.
     */
    image?: (number | null) | Media;
    /**
     * Optional caption shown under the image.
     */
    imageCaption?: string | null;
  };
  closing?: {
    eyebrow?: string | null;
    heading?: string | null;
    lead?: string | null;
    primaryCta?: {
      /**
       * Leave empty to omit this action from the page.
       */
      label?: string | null;
      route?:
        ('products' | 'customized-solutions' | 'quality-certifications' | 'contact-us' | 'request-a-quote') | null;
    };
    routes?:
      | {
          label: string;
          route?:
            ('products' | 'customized-solutions' | 'quality-certifications' | 'contact-us' | 'request-a-quote') | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Optional. Every field falls back to the page's own content when left empty — an empty title or description is never shipped.
   */
  seo?: {
    /**
     * Falls back to the page title.
     */
    metaTitle?: string | null;
    /**
     * Falls back to the page's own content. Aim for roughly 150–160 characters.
     */
    metaDescription?: string | null;
    /**
     * Override only. Leave empty unless this page deliberately points at another URL.
     */
    canonicalUrl?: string | null;
    /**
     * Falls back to the meta title.
     */
    ogTitle?: string | null;
    /**
     * Falls back to the meta description.
     */
    ogDescription?: string | null;
    /**
     * Shown when the page is shared. 1200×630 is the platform convention. Separate from any hero image on purpose.
     */
    socialImage?: (number | null) | Media;
    twitterCardType?: ('summary' | 'summary_large_image') | null;
    /**
     * Falls back to the Open Graph title.
     */
    twitterTitle?: string | null;
    /**
     * Falls back to the Open Graph description.
     */
    twitterDescription?: string | null;
    /**
     * Falls back to the social image above.
     */
    twitterImage?: (number | null) | Media;
    /**
     * Uncheck to mark this page noindex.
     */
    robotsIndex?: boolean | null;
    /**
     * Uncheck to mark this page nofollow.
     */
    robotsFollow?: boolean | null;
    /**
     * Internal content planning. Not a ranking factor in modern search.
     */
    keywords?: string[] | null;
    /**
     * Advanced. Replaces the automatically generated JSON-LD for this page. Leave empty to use the automatic output.
     */
    structuredDataOverride?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The Customized Solutions page copy. The request form itself is not CMS content — its fields, validation and consent text belong to the API.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customized-solutions".
 */
export interface CustomizedSolution {
  id: number;
  hero: {
    eyebrow?: string | null;
    /**
     * The page's H1. Required — a document with no heading is treated as unconfigured and is not served.
     */
    title: string;
    supportingText?: string | null;
    requestCta?: {
      /**
       * Wording only. This button always jumps to the request form on this page; its target is fixed in code. Leave empty to omit this action.
       */
      label?: string | null;
    };
    routeCta?: {
      /**
       * Leave empty to omit this action from the page.
       */
      label?: string | null;
      route?:
        ('products' | 'customized-solutions' | 'quality-certifications' | 'contact-us' | 'request-a-quote') | null;
    };
  };
  introduction?: {
    heading?: string | null;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    bodyHtml?: string | null;
  };
  process?: {
    heading?: string | null;
    lead?: string | null;
    /**
     * The stages in order. Their numbering is their position and is not stored separately.
     */
    steps?:
      | {
          name: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Claim-controlled requirement dimensions. Do not add availability, performance, MOQ or formulation claims without approved evidence.
   */
  whatCanWeCustomize?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Every field falls back to the page's own content when left empty — an empty title or description is never shipped.
   */
  seo?: {
    /**
     * Falls back to the page title.
     */
    metaTitle?: string | null;
    /**
     * Falls back to the page's own content. Aim for roughly 150–160 characters.
     */
    metaDescription?: string | null;
    /**
     * Override only. Leave empty unless this page deliberately points at another URL.
     */
    canonicalUrl?: string | null;
    /**
     * Falls back to the meta title.
     */
    ogTitle?: string | null;
    /**
     * Falls back to the meta description.
     */
    ogDescription?: string | null;
    /**
     * Shown when the page is shared. 1200×630 is the platform convention. Separate from any hero image on purpose.
     */
    socialImage?: (number | null) | Media;
    twitterCardType?: ('summary' | 'summary_large_image') | null;
    /**
     * Falls back to the Open Graph title.
     */
    twitterTitle?: string | null;
    /**
     * Falls back to the Open Graph description.
     */
    twitterDescription?: string | null;
    /**
     * Falls back to the social image above.
     */
    twitterImage?: (number | null) | Media;
    /**
     * Uncheck to mark this page noindex.
     */
    robotsIndex?: boolean | null;
    /**
     * Uncheck to mark this page nofollow.
     */
    robotsFollow?: boolean | null;
    /**
     * Internal content planning. Not a ranking factor in modern search.
     */
    keywords?: string[] | null;
    /**
     * Advanced. Replaces the automatically generated JSON-LD for this page. Leave empty to use the automatic output.
     */
    structuredDataOverride?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The Quality & Certifications page. No certificate, standard, licence, accreditation, issuing body, number or validity date is modelled anywhere in this Global — the certifications section states that the list is unconfirmed, and that is all it can state.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quality-certifications".
 */
export interface QualityCertification {
  id: number;
  hero: {
    eyebrow?: string | null;
    /**
     * The page's H1. Required — a document with no heading is treated as unconfigured and is not served.
     */
    title: string;
    supportingText?: string | null;
    /**
     * Heading for the stage chain beside the hero. The chain itself is read from the testing stages below — it is not a second list.
     */
    indexLabel?: string | null;
    primaryCta?: {
      /**
       * Leave empty to omit this action from the page.
       */
      label?: string | null;
      route?:
        ('products' | 'customized-solutions' | 'quality-certifications' | 'contact-us' | 'request-a-quote') | null;
    };
    secondaryCta?: {
      /**
       * Leave empty to omit this action from the page.
       */
      label?: string | null;
      route?:
        ('products' | 'customized-solutions' | 'quality-certifications' | 'contact-us' | 'request-a-quote') | null;
    };
  };
  /**
   * The stages at which testing happens. Their order is their position in the list — a batch meets them in sequence.
   */
  approach?: {
    eyebrow?: string | null;
    heading?: string | null;
    lead?: string | null;
    stages?:
      | {
          name: string;
          /**
           * Where the stage sits in the material's passage — not what is done inside it. No approved document describes the contents of any stage, so describing one here would be writing a procedure.
           */
          when: string;
          id?: string | null;
        }[]
      | null;
    /**
     * States what this section does not publish. A reader shown three stage names fills in their contents unless told the page is not saying.
     */
    footnote?: string | null;
  };
  /**
   * Property names only. A property name does NOT establish that Sam Group performs that test, performs it in-house, owns the equipment, holds an accreditation for it, or can meet any numeric value. No approved document names a single test standard. Do not add a method designation, a test condition or a result to any wording here.
   */
  laboratory?: {
    eyebrow?: string | null;
    heading?: string | null;
    lead?: string | null;
    registerLabel?: string | null;
    /**
     * How the register is ordered — e.g. the source's own order.
     */
    orderNote?: string | null;
    /**
     * A name, and nothing else. There is deliberately no field here for a test method, a condition, a unit, a value, a result, an accreditation, an instrument or an in-house marker — a wrong method number cited against a real property is a technical error a buyer would specify against.
     */
    properties?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
    unpublishedHeading?: string | null;
    /**
     * Each attribute the register withholds, with the reason, shown to the reader. Removing the in-house/external entry would let a 'Laboratory Capability' heading be read as claiming all of them in-house.
     */
    unpublished?:
      | {
          name: string;
          why: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional. Instruments and bench, not portraits. The section renders with no figure at all when this is empty.
     */
    image?: (number | null) | Media;
    /**
     * Optional caption shown under the image.
     */
    imageCaption?: string | null;
  };
  /**
   * This section publishes ONE statement and no list. There is no field here for a certificate, standard, licence, accreditation, issuing body, certificate number, validity date, mark, logo or link, and none may be added — the real list is unconfirmed, and a placeholder is the one claim on this page a reader has no way to check. The Certifications collection with its Admin-only publish gate is a later gate.
   */
  certifications?: {
    eyebrow?: string | null;
    heading?: string | null;
    /**
     * The state, as words. It is rendered as text beside a decorative mark, never as a colour alone.
     */
    status?: string | null;
    statement?: string | null;
    note?: string | null;
  };
  /**
   * An informational register of the paperwork a shipment carries. Nothing here is a download: there is no file field and no link field, and the note below must keep saying so — six document names under a heading are read as six files otherwise.
   */
  documentation?: {
    eyebrow?: string | null;
    heading?: string | null;
    lead?: string | null;
    registerLabel?: string | null;
    documents?:
      | {
          name: string;
          /**
           * Optional. What the document is issued against — only where an approved document states it.
           */
          scope?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * The line that keeps this register from reading as a download list. Do not remove it while none of these can be obtained from this site.
     */
    note?: string | null;
  };
  sampling: {
    eyebrow?: string | null;
    /**
     * The policy itself, in one sentence. It is the section's heading — there is no separate heading field.
     */
    statement: string;
    familiesLabel?: string | null;
    /**
     * Which product families the policy is confirmed for. Payload stores identifiers only — the family's name and its page address come from the product catalogue, never from here. Select at least one: the policy is published with its scope or not at all.
     */
    families: (
      | 'base-oils'
      | 'lubricant-additives'
      | 'engine-oils-automotive-lubricants'
      | 'industrial-oils-lubricants'
      | 'marine-oils-lubricants'
      | 'antifreeze-coolants'
    )[];
    /**
     * States that the policy is not extended beyond the families selected above. Publishing the policy without its limit is a broader promise than the documentation makes.
     */
    limit?: string | null;
  };
  closing?: {
    eyebrow?: string | null;
    heading?: string | null;
    lead?: string | null;
    primaryCta?: {
      /**
       * Leave empty to omit this action from the page.
       */
      label?: string | null;
      route?:
        ('products' | 'customized-solutions' | 'quality-certifications' | 'contact-us' | 'request-a-quote') | null;
    };
    routes?:
      | {
          label: string;
          route?:
            ('products' | 'customized-solutions' | 'quality-certifications' | 'contact-us' | 'request-a-quote') | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Optional. Every field falls back to the page's own content when left empty — an empty title or description is never shipped.
   */
  seo?: {
    /**
     * Falls back to the page title.
     */
    metaTitle?: string | null;
    /**
     * Falls back to the page's own content. Aim for roughly 150–160 characters.
     */
    metaDescription?: string | null;
    /**
     * Override only. Leave empty unless this page deliberately points at another URL.
     */
    canonicalUrl?: string | null;
    /**
     * Falls back to the meta title.
     */
    ogTitle?: string | null;
    /**
     * Falls back to the meta description.
     */
    ogDescription?: string | null;
    /**
     * Shown when the page is shared. 1200×630 is the platform convention. Separate from any hero image on purpose.
     */
    socialImage?: (number | null) | Media;
    twitterCardType?: ('summary' | 'summary_large_image') | null;
    /**
     * Falls back to the Open Graph title.
     */
    twitterTitle?: string | null;
    /**
     * Falls back to the Open Graph description.
     */
    twitterDescription?: string | null;
    /**
     * Falls back to the social image above.
     */
    twitterImage?: (number | null) | Media;
    /**
     * Uncheck to mark this page noindex.
     */
    robotsIndex?: boolean | null;
    /**
     * Uncheck to mark this page nofollow.
     */
    robotsFollow?: boolean | null;
    /**
     * Internal content planning. Not a ranking factor in modern search.
     */
    keywords?: string[] | null;
    /**
     * Advanced. Replaces the automatically generated JSON-LD for this page. Leave empty to use the automatic output.
     */
    structuredDataOverride?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Official contact channels shown on Contact Us and used in structured data. Leave an unconfirmed channel empty.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us".
 */
export interface ContactUs {
  id: number;
  /**
   * Main office number, including country code.
   */
  mainPhone?: string | null;
  /**
   * Sales team number, including country code.
   */
  salesPhone?: string | null;
  generalEmail?: string | null;
  salesEmail?: string | null;
  whatsappUrl?: string | null;
  linkedinUrl?: string | null;
  instagramUrl?: string | null;
  telegramUrl?: string | null;
  /**
   * Public postal address. Localize it for each site language.
   */
  address?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us_select".
 */
export interface AboutUsSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        supportingText?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              route?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              route?: T;
            };
        image?: T;
        imageCaption?: T;
      };
  whoWeAre?:
    | T
    | {
        heading?: T;
        body?: T;
        bodyHtml?: T;
        positions?:
          | T
          | {
              term?: T;
              note?: T;
              id?: T;
            };
        image?: T;
        imageCaption?: T;
      };
  expertise?:
    | T
    | {
        heading?: T;
        lead?: T;
        items?:
          | T
          | {
              name?: T;
              note?: T;
              icon?: T;
              id?: T;
            };
      };
  competitiveAdvantages?:
    | T
    | {
        heading?: T;
        lead?: T;
        items?:
          | T
          | {
              name?: T;
              note?: T;
              icon?: T;
              id?: T;
            };
      };
  team?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        lead?: T;
        functions?:
          | T
          | {
              name?: T;
              note?: T;
              id?: T;
            };
        image?: T;
        imageCaption?: T;
      };
  qualityStandards?:
    | T
    | {
        heading?: T;
        lead?: T;
        items?:
          | T
          | {
              name?: T;
              note?: T;
              id?: T;
            };
        footnote?: T;
        footnoteCta?:
          | T
          | {
              label?: T;
              route?: T;
            };
        image?: T;
        imageCaption?: T;
      };
  closing?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        lead?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              route?: T;
            };
        routes?:
          | T
          | {
              label?: T;
              route?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        socialImage?: T;
        twitterCardType?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        robotsIndex?: T;
        robotsFollow?: T;
        keywords?: T;
        structuredDataOverride?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customized-solutions_select".
 */
export interface CustomizedSolutionsSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        supportingText?: T;
        requestCta?:
          | T
          | {
              label?: T;
            };
        routeCta?:
          | T
          | {
              label?: T;
              route?: T;
            };
      };
  introduction?:
    | T
    | {
        heading?: T;
        body?: T;
        bodyHtml?: T;
      };
  process?:
    | T
    | {
        heading?: T;
        lead?: T;
        steps?:
          | T
          | {
              name?: T;
              description?: T;
              id?: T;
            };
      };
  whatCanWeCustomize?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        socialImage?: T;
        twitterCardType?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        robotsIndex?: T;
        robotsFollow?: T;
        keywords?: T;
        structuredDataOverride?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quality-certifications_select".
 */
export interface QualityCertificationsSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        supportingText?: T;
        indexLabel?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              route?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              route?: T;
            };
      };
  approach?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        lead?: T;
        stages?:
          | T
          | {
              name?: T;
              when?: T;
              id?: T;
            };
        footnote?: T;
      };
  laboratory?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        lead?: T;
        registerLabel?: T;
        orderNote?: T;
        properties?:
          | T
          | {
              name?: T;
              id?: T;
            };
        unpublishedHeading?: T;
        unpublished?:
          | T
          | {
              name?: T;
              why?: T;
              id?: T;
            };
        image?: T;
        imageCaption?: T;
      };
  certifications?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        status?: T;
        statement?: T;
        note?: T;
      };
  documentation?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        lead?: T;
        registerLabel?: T;
        documents?:
          | T
          | {
              name?: T;
              scope?: T;
              id?: T;
            };
        note?: T;
      };
  sampling?:
    | T
    | {
        eyebrow?: T;
        statement?: T;
        familiesLabel?: T;
        families?: T;
        limit?: T;
      };
  closing?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        lead?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              route?: T;
            };
        routes?:
          | T
          | {
              label?: T;
              route?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        socialImage?: T;
        twitterCardType?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        robotsIndex?: T;
        robotsFollow?: T;
        keywords?: T;
        structuredDataOverride?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us_select".
 */
export interface ContactUsSelect<T extends boolean = true> {
  mainPhone?: T;
  salesPhone?: T;
  generalEmail?: T;
  salesEmail?: T;
  whatsappUrl?: T;
  linkedinUrl?: T;
  instagramUrl?: T;
  telegramUrl?: T;
  address?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}