// Shared request/response DTO types for apps/web and apps/api (see PROJECT_STRUCTURE.md).
// Types only — never a runtime value; ./seo.ts explains why that constraint is structural
// rather than stylistic.
export type {
  AdminCustomFormulationRequestDetailResponse,
  AdminCustomFormulationRequestListItemResponse,
  AdminInquiryDetailResponse,
  AdminInquiryListItemResponse,
  AdminInquiryType,
  LeadHistoryEntry,
  LeadStatus,
  LeadWorkflowState,
} from "./admin-leads";
export type {
  ApiErrorCode,
  ApiErrorDetail,
  ApiErrorResponse,
  ApiMeta,
  ApiSuccessResponse,
} from "./api";
export type {
  BlogCategoryResponse,
  BlogPostDetailResponse,
  BlogPostListItemResponse,
  BlogTagResponse,
} from "./blog";
export type {
  CategoryResponse,
  ProductDetailResponse,
  ProductImageResponse,
  ProductListItemResponse,
  ProductSegmentResponse,
  ProductSpecificationResponse,
  ProductTypeResponse,
} from "./catalog";
export type {
  ReviewBlocker,
  ReviewBlockerCode,
  ReviewClaimKind,
  ReviewClaimValue,
  ReviewDetailResponse,
  ReviewDocumentRef,
  ReviewEvidenceEntry,
  ReviewEvidenceRole,
  ReviewExtractionMethod,
  ReviewGradeRef,
  ReviewHistoryDecision,
  ReviewHistoryEntry,
  ReviewLocatorType,
  ReviewMappingConfidence,
  ReviewMappingRef,
  ReviewMethodRequirement,
  ReviewProductRef,
  ReviewQueueItemResponse,
  ReviewQueueSort,
  ReviewResultBasis,
  ReviewSpecificationValue,
  ReviewStatus,
  ReviewSubjectType,
  ReviewUnitClassification,
  ReviewValueKind,
  ReviewValueType,
  ReviewWarning,
  ReviewWarningCode,
} from "./catalog-review";
export type {
  AboutUsClosing,
  AboutUsContent,
  AboutUsExpertise,
  AboutUsHero,
  AboutUsQualityStandards,
  AboutUsResponse,
  AboutUsWhoWeAre,
  ContentAnchorCta,
  ContentCta,
  ContentFigure,
  ContentGlobalResponse,
  ContentImage,
  ContentPageResponse,
  ContentRouteKey,
  CustomizedSolutionsContent,
  CustomizedSolutionsHero,
  CustomizedSolutionsIntroduction,
  CustomizedSolutionsProcess,
  CustomizedSolutionsResponse,
  ProductFamilyKey,
  QualityApproach,
  QualityCertificationsContent,
  QualityCertificationsHero,
  QualityCertificationsResponse,
  QualityCertificationsSection,
  QualityClosing,
  QualityDocument,
  QualityDocumentation,
  QualityLaboratory,
  QualityProperty,
  QualitySampling,
  QualityStage,
  QualityUnpublishedAttribute,
} from "./content";
export type { LocaleDirection, LocaleResponse } from "./locale";
export type { SeoAlternate, SeoFields, SeoImage, TwitterCardType } from "./seo";
