/**
 * The 100 authoritative workbook rows, frozen as a test expectation.
 *
 * This is NOT a second source of truth and nothing in the importer reads it. The
 * authoritative workbook is not in version control (it was supplied as a file), so
 * without this the suite could assert nothing about the 100 rows on a machine that does
 * not have it. Two tests keep the fixture honest:
 *
 *   * `workbook-parser.spec.ts` parses the REAL workbook and asserts it matches this
 *     fixture exactly, whenever CATALOG_WORKBOOK points at it. That test is skipped —
 *     loudly — when the file is absent, and it is the one that proves the fixture is
 *     still a true copy.
 *   * every other test builds its plan from this fixture, so the ratified counts are
 *     verifiable on any machine.
 *
 * Regenerate it, never hand-edit it: a fixture edited to make a test pass is a test
 * that has stopped checking anything.
 */

import type { ParsedWorkbook } from "../workbook-parser";

export const WORKBOOK_FIXTURE: ParsedWorkbook = {
  sheetName: "محصولات",
  rows: [
    {
      sheetName: "محصولات",
      rowNumber: 3,
      name: "CK-4 10W-40",
      rawName: "CK-4  10W-40",
      productTypeLabel: "دیزلی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: true,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/7jisz5ybebvu4_y",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/7jisz5ybebvu4_y",
    },
    {
      sheetName: "محصولات",
      rowNumber: 6,
      name: "CJ-4 10W-40",
      rawName: "CJ-4  10W-40",
      productTypeLabel: "دیزلی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/0a3p-fth3cmbzl7",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/0a3p-fth3cmbzl7",
    },
    {
      sheetName: "محصولات",
      rowNumber: 9,
      name: "CI-4 10W-40",
      rawName: "CI-4 10W-40",
      productTypeLabel: "دیزلی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/2enscx8i28yqzjf",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/2enscx8i28yqzjf",
    },
    {
      sheetName: "محصولات",
      rowNumber: 12,
      name: "CI-4 15W-40",
      rawName: "CI-4 15W-40",
      productTypeLabel: "دیزلی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/5bwmb9f9jp5n_10",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/5bwmb9f9jp5n_10",
    },
    {
      sheetName: "محصولات",
      rowNumber: 15,
      name: "CI-4 20W-50",
      rawName: "CI-4  20W-50",
      productTypeLabel: "دیزلی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/lbOEZKCrex",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/lbOEZKCrex",
    },
    {
      sheetName: "محصولات",
      rowNumber: 18,
      name: "CH-4 15W-40",
      rawName: "CH-4  15W-40",
      productTypeLabel: "دیزلی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/2-n8u3z3lzc_pqt",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/2-n8u3z3lzc_pqt",
    },
    {
      sheetName: "محصولات",
      rowNumber: 21,
      name: "CH-4 20W-50",
      rawName: "CH-4  20W-50",
      productTypeLabel: "دیزلی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/0qbget19442rjwu",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/0qbget19442rjwu",
    },
    {
      sheetName: "محصولات",
      rowNumber: 24,
      name: "CF-4 15W-40",
      rawName: "CF-4  15W-40",
      productTypeLabel: "دیزلی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/qosd3kr5985dg4-",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/qosd3kr5985dg4-",
    },
    {
      sheetName: "محصولات",
      rowNumber: 27,
      name: "CF-4 20W-50",
      rawName: "CF-4  20W-50",
      productTypeLabel: "دیزلی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/17kqpspapn0iyp8",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/17kqpspapn0iyp8",
    },
    {
      sheetName: "محصولات",
      rowNumber: 30,
      name: "CJ4 Grade",
      rawName: "CJ4 Grade",
      productTypeLabel: "دیزلی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 33,
      name: "CI4 Grade",
      rawName: "CI4 Grade",
      productTypeLabel: "دیزلی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 36,
      name: "CH-4 Grade",
      rawName: "CH-4 Grade",
      productTypeLabel: "دیزلی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 39,
      name: "CD Grade",
      rawName: "CD Grade",
      productTypeLabel: "دیزلی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 42,
      name: "SN 5W-30",
      rawName: "SN   5W-30",
      productTypeLabel: "بنزینی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/86si_dolr8xwcbw",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/86si_dolr8xwcbw",
    },
    {
      sheetName: "محصولات",
      rowNumber: 45,
      name: "SN 5W-40",
      rawName: "SN 5W-40",
      productTypeLabel: "بنزینی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/ph-o7ebvwqssoth",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/ph-o7ebvwqssoth",
    },
    {
      sheetName: "محصولات",
      rowNumber: 48,
      name: "SN 10W-40",
      rawName: "SN 10W-40",
      productTypeLabel: "بنزینی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/i4xkwexl56qll9p",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/i4xkwexl56qll9p",
    },
    {
      sheetName: "محصولات",
      rowNumber: 51,
      name: "SM 10W-40",
      rawName: "SM  10W-40",
      productTypeLabel: "بنزینی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/oLdlx1m5hY",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/oLdlx1m5hY",
    },
    {
      sheetName: "محصولات",
      rowNumber: 54,
      name: "SM 20W-50",
      rawName: "SM 20W-50",
      productTypeLabel: "بنزینی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/PhLhFUandi",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/PhLhFUandi",
    },
    {
      sheetName: "محصولات",
      rowNumber: 57,
      name: "SL 10W-40",
      rawName: "SL 10W-40",
      productTypeLabel: "بنزینی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/JIVTSBac7b",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/JIVTSBac7b",
    },
    {
      sheetName: "محصولات",
      rowNumber: 60,
      name: "SL 20W-50",
      rawName: "SL 20W-50",
      productTypeLabel: "بنزینی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/9jwy0kucflsp5lh",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/9jwy0kucflsp5lh",
    },
    {
      sheetName: "محصولات",
      rowNumber: 63,
      name: "SJ 10W-40",
      rawName: "SJ 10W-40",
      productTypeLabel: "بنزینی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/8mfZpVb3zB",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/8mfZpVb3zB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 66,
      name: "SJ 20W-50",
      rawName: "SJ 20W-50",
      productTypeLabel: "بنزینی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/zAkb7Qcw0w",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/zAkb7Qcw0w",
    },
    {
      sheetName: "محصولات",
      rowNumber: 69,
      name: "SN Grade",
      rawName: "SN Grade",
      productTypeLabel: "بنزینی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 72,
      name: "SM Grade",
      rawName: "SM Grade",
      productTypeLabel: "بنزینی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 75,
      name: "SL Grade",
      rawName: "SL Grade",
      productTypeLabel: "بنزینی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 78,
      name: "SJ Grade",
      rawName: "SJ Grade",
      productTypeLabel: "بنزینی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 81,
      name: "SG Grade",
      rawName: "SG Grade",
      productTypeLabel: "بنزینی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 84,
      name: "SF Grade",
      rawName: "SF Grade",
      productTypeLabel: "بنزینی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 87,
      name: "SC Grade",
      rawName: "SC Grade",
      productTypeLabel: "بنزینی",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 90,
      name: "locomotive Oil",
      rawName: "locomotive Oil",
      productTypeLabel: "روغن لوکوموتیو",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 93,
      name: "Racing Grade",
      rawName: "Racing Grade",
      productTypeLabel: "روغن موتور سیکلت",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 96,
      name: "SN Grade",
      rawName: "SN Grade",
      productTypeLabel: "روغن موتور سیکلت",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 99,
      name: "SG Grade",
      rawName: "SG Grade",
      productTypeLabel: "روغن موتور سیکلت",
      categoryLabel: "روغن موتور Engine oil",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 102,
      name: "Extreme Pressure (EP)",
      rawName: "Extreme Pressure (EP)",
      productTypeLabel: "",
      categoryLabel: "روغن های صنعتی Industrial Oils",
      categoryIsOwnCell: true,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/l3EIPgKZoz",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/l3EIPgKZoz",
    },
    {
      sheetName: "محصولات",
      rowNumber: 105,
      name: "Polyalphaolefin (PAO)",
      rawName: "Polyalphaolefin (PAO)",
      productTypeLabel: "",
      categoryLabel: "روغن های صنعتی Industrial Oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/vCa6469pwN",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/vCa6469pwN",
    },
    {
      sheetName: "محصولات",
      rowNumber: 108,
      name: "Polyalkylene Glycol (PAG)",
      rawName: "Polyalkylene Glycol (PAG)",
      productTypeLabel: "",
      categoryLabel: "روغن های صنعتی Industrial Oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/VMubhPSdMH",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/VMubhPSdMH",
    },
    {
      sheetName: "محصولات",
      rowNumber: 111,
      name: "TURBINE TECH Radial Flow",
      rawName: "TURBINE TECH Radial Flow",
      productTypeLabel: "",
      categoryLabel: "روغن های صنعتی Industrial Oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/JdxS4nnbsQ",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/JdxS4nnbsQ",
    },
    {
      sheetName: "محصولات",
      rowNumber: 114,
      name: "TURBINE TECH Gas Turbine (GT)",
      rawName: "TURBINE TECH Gas Turbine (GT)",
      productTypeLabel: "",
      categoryLabel: "روغن های صنعتی Industrial Oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/Zjnc5YVm1f",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/Zjnc5YVm1f",
    },
    {
      sheetName: "محصولات",
      rowNumber: 117,
      name: "COMPRESSOR TECH",
      rawName: "COMPRESSOR TECH",
      productTypeLabel: "",
      categoryLabel: "روغن های صنعتی Industrial Oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/RPztnzqMnj",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/RPztnzqMnj",
    },
    {
      sheetName: "محصولات",
      rowNumber: 120,
      name: "COMPRESSOR TECH Polyalphaolefin- Synthetic (PAO-S)",
      rawName: "COMPRESSOR TECH Polyalphaolefin- Synthetic (PAO-S)",
      productTypeLabel: "",
      categoryLabel: "روغن های صنعتی Industrial Oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/GiuHxWn477",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/GiuHxWn477",
    },
    {
      sheetName: "محصولات",
      rowNumber: 123,
      name: "COMPRESSOR TECH Refrigeration Compressor Oil",
      rawName: "COMPRESSOR TECH Refrigeration Compressor Oil",
      productTypeLabel: "",
      categoryLabel: "روغن های صنعتی Industrial Oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/mAeDbYOmaW",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/mAeDbYOmaW",
    },
    {
      sheetName: "محصولات",
      rowNumber: 126,
      name: "ROLLING TECH Rolling Oil",
      rawName: "ROLLING TECH Rolling Oil",
      productTypeLabel: "",
      categoryLabel: "روغن های صنعتی Industrial Oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/LH31K6SEV8",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/LH31K6SEV8",
    },
    {
      sheetName: "محصولات",
      rowNumber: 129,
      name: "HEAT TECH Heat Transfer Oil",
      rawName: "HEAT TECH Heat Transfer Oil",
      productTypeLabel: "",
      categoryLabel: "روغن های صنعتی Industrial Oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/fs4o2SCshm",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/fs4o2SCshm",
    },
    {
      sheetName: "محصولات",
      rowNumber: 132,
      name: "HEAT TECH Heat Metal Oil",
      rawName: "HEAT TECH Heat Metal Oil",
      productTypeLabel: "",
      categoryLabel: "روغن های صنعتی Industrial Oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/gwT3ds8CFB",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/gwT3ds8CFB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 135,
      name: "CUTTING TECH Cutting Oil",
      rawName: "CUTTING TECH Cutting Oil",
      productTypeLabel: "",
      categoryLabel: "روغن های صنعتی Industrial Oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/lIA3fbUe82",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/lIA3fbUe82",
    },
    {
      sheetName: "محصولات",
      rowNumber: 138,
      name: "FLASHING TECH Flashing Oil",
      rawName: "FLASHING TECH Flashing Oil",
      productTypeLabel: "",
      categoryLabel: "روغن های صنعتی Industrial Oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/jDF8HSWJaa",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/jDF8HSWJaa",
    },
    {
      sheetName: "محصولات",
      rowNumber: 141,
      name: "hydraulic oil- HL Grade",
      rawName: "hydraulic oil- HL Grade",
      productTypeLabel: "",
      categoryLabel: "روغن های صنعتی Industrial Oils",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 144,
      name: "hydraulic Oil- HH Grade",
      rawName: "hydraulic Oil- HH Grade",
      productTypeLabel: "",
      categoryLabel: "روغن های صنعتی Industrial Oils",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 147,
      name: "Circulating oil",
      rawName: "Circulating oil",
      productTypeLabel: "",
      categoryLabel: "روغن های صنعتی Industrial Oils",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 150,
      name: "Heat Transfer oil",
      rawName: "Heat Transfer oil",
      productTypeLabel: "",
      categoryLabel: "روغن های صنعتی Industrial Oils",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 153,
      name: "quenching oil",
      rawName: "quenching oil",
      productTypeLabel: "",
      categoryLabel: "روغن های صنعتی Industrial Oils",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 156,
      name: "Turbine oil",
      rawName: "Turbine oil",
      productTypeLabel: "",
      categoryLabel: "روغن های صنعتی Industrial Oils",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 159,
      name: "Compressor oil -VB",
      rawName: "Compressor oil -VB",
      productTypeLabel: "",
      categoryLabel: "روغن های صنعتی Industrial Oils",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 162,
      name: "Refrigerator compressor oil-KD",
      rawName: "Refrigerator compressor oil-KD",
      productTypeLabel: "",
      categoryLabel: "روغن های صنعتی Industrial Oils",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 165,
      name: "GL-5 75W-80",
      rawName: "GL-5 75W-80",
      productTypeLabel: "دنده دستی",
      categoryLabel: "روغن های دنده Gear oils",
      categoryIsOwnCell: true,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/xltdlws8jt4f6ah",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/xltdlws8jt4f6ah",
    },
    {
      sheetName: "محصولات",
      rowNumber: 168,
      name: "GL-5 75W-90",
      rawName: "GL-5 75W-90",
      productTypeLabel: "دنده دستی",
      categoryLabel: "روغن های دنده Gear oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/qozz3str_pqdkar",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/qozz3str_pqdkar",
    },
    {
      sheetName: "محصولات",
      rowNumber: 171,
      name: "GL-5 80W-90",
      rawName: "GL-5 80W-90",
      productTypeLabel: "دنده دستی",
      categoryLabel: "روغن های دنده Gear oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/MJT3yQw8AY",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/MJT3yQw8AY",
    },
    {
      sheetName: "محصولات",
      rowNumber: 174,
      name: "GL-5 85W-90",
      rawName: "GL-5 85W-90",
      productTypeLabel: "دنده دستی",
      categoryLabel: "روغن های دنده Gear oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/2ofb8iyj6lmn3m4",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/2ofb8iyj6lmn3m4",
    },
    {
      sheetName: "محصولات",
      rowNumber: 177,
      name: "GL-5 85W-140",
      rawName: "GL-5 85W-140",
      productTypeLabel: "دنده دستی",
      categoryLabel: "روغن های دنده Gear oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/1_s5csf_gan0bug",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/1_s5csf_gan0bug",
    },
    {
      sheetName: "محصولات",
      rowNumber: 180,
      name: "DCT",
      rawName: "DCT",
      productTypeLabel: "اتوماتیک",
      categoryLabel: "روغن های دنده Gear oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/aa66xhpl32ss3yg",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/aa66xhpl32ss3yg",
    },
    {
      sheetName: "محصولات",
      rowNumber: 183,
      name: "DEX VI",
      rawName: "DEX VI",
      productTypeLabel: "اتوماتیک",
      categoryLabel: "روغن های دنده Gear oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/vqzalq_thlnupzq",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/vqzalq_thlnupzq",
    },
    {
      sheetName: "محصولات",
      rowNumber: 186,
      name: "SP-4",
      rawName: "SP-4",
      productTypeLabel: "اتوماتیک",
      categoryLabel: "روغن های دنده Gear oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/anery_pji_pc24y",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/anery_pji_pc24y",
    },
    {
      sheetName: "محصولات",
      rowNumber: 189,
      name: "CVT",
      rawName: "CVT",
      productTypeLabel: "اتوماتیک",
      categoryLabel: "روغن های دنده Gear oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/cz-ko9d1rvnyyi5",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/cz-ko9d1rvnyyi5",
    },
    {
      sheetName: "محصولات",
      rowNumber: 192,
      name: "DEX III",
      rawName: "DEX III",
      productTypeLabel: "اتوماتیک",
      categoryLabel: "روغن های دنده Gear oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/ta45rcfi_uhx8mq",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/ta45rcfi_uhx8mq",
    },
    {
      sheetName: "محصولات",
      rowNumber: 195,
      name: "MV",
      rawName: "MV",
      productTypeLabel: "اتوماتیک",
      categoryLabel: "روغن های دنده Gear oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/fYXwL2Svz6",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/fYXwL2Svz6",
    },
    {
      sheetName: "محصولات",
      rowNumber: 198,
      name: "AL-4",
      rawName: "AL-4",
      productTypeLabel: "اتوماتیک",
      categoryLabel: "روغن های دنده Gear oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/rcsip_um7fxjw98",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/rcsip_um7fxjw98",
    },
    {
      sheetName: "محصولات",
      rowNumber: 201,
      name: "ISO VG 32",
      rawName: "ISO VG 32",
      productTypeLabel: "",
      categoryLabel: "روغن های سیستم هیدرولیک Hydraulic oils",
      categoryIsOwnCell: true,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/KbdbrTFaXw",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/KbdbrTFaXw",
    },
    {
      sheetName: "محصولات",
      rowNumber: 204,
      name: "ISO VG 46",
      rawName: "ISO VG 46",
      productTypeLabel: "",
      categoryLabel: "روغن های سیستم هیدرولیک Hydraulic oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/xrizukl9dcyqrl0",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/xrizukl9dcyqrl0",
    },
    {
      sheetName: "محصولات",
      rowNumber: 207,
      name: "ISO VG 68",
      rawName: "ISO VG 68",
      productTypeLabel: "",
      categoryLabel: "روغن های سیستم هیدرولیک Hydraulic oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/lBsunzBKc7",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/lBsunzBKc7",
    },
    {
      sheetName: "محصولات",
      rowNumber: 210,
      name: "ISO VG 100",
      rawName: "ISO VG 100",
      productTypeLabel: "",
      categoryLabel: "روغن های سیستم هیدرولیک Hydraulic oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/rcmbToEguy",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/rcmbToEguy",
    },
    {
      sheetName: "محصولات",
      rowNumber: 213,
      name: "REWARD TECH Marine Special",
      rawName: "REWARD TECH Marine Special",
      productTypeLabel: "",
      categoryLabel: "روغن های دریایی Marine Oils",
      categoryIsOwnCell: true,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/eI87yELTsc",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/eI87yELTsc",
    },
    {
      sheetName: "محصولات",
      rowNumber: 216,
      name: "REWARD SUPER TECH Semi Synthetic",
      rawName: "REWARD SUPER TECH Semi Synthetic",
      productTypeLabel: "",
      categoryLabel: "روغن های دریایی Marine Oils",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/jPuaig86aX",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/jPuaig86aX",
    },
    {
      sheetName: "محصولات",
      rowNumber: 219,
      name: "TWO-Stroke Engine Oil",
      rawName: "TWO-Stroke Engine Oil",
      productTypeLabel: "",
      categoryLabel: "روغن های دریایی Marine Oils",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 222,
      name: "LENJ oil",
      rawName: "LENJ oil",
      productTypeLabel: "",
      categoryLabel: "روغن های دریایی Marine Oils",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 225,
      name: "super trunk oil",
      rawName: "super trunk oil",
      productTypeLabel: "",
      categoryLabel: "روغن های دریایی Marine Oils",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 228,
      name: "trunk oil",
      rawName: "trunk oil",
      productTypeLabel: "",
      categoryLabel: "روغن های دریایی Marine Oils",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 231,
      name: "special trunk oil",
      rawName: "special trunk oil",
      productTypeLabel: "",
      categoryLabel: "روغن های دریایی Marine Oils",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 234,
      name: "ATF Grade",
      rawName: "ATF Grade",
      productTypeLabel: "",
      categoryLabel: "روغن های دریایی Marine Oils",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 237,
      name: "GL-5 Grade",
      rawName: "GL-5 Grade",
      productTypeLabel: "",
      categoryLabel: "روغن های دریایی Marine Oils",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 240,
      name: "GL-4 Grade",
      rawName: "GL-4 Grade",
      productTypeLabel: "",
      categoryLabel: "روغن های دریایی Marine Oils",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 243,
      name: "GL-3 Grade",
      rawName: "GL-3 Grade",
      productTypeLabel: "",
      categoryLabel: "روغن های دریایی Marine Oils",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 246,
      name: "GL-I Grade",
      rawName: "GL-I Grade",
      productTypeLabel: "",
      categoryLabel: "روغن های دریایی Marine Oils",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
    {
      sheetName: "محصولات",
      rowNumber: 249,
      name: "Ash-free Antioxidant",
      rawName: "Ash-free Antioxidant",
      productTypeLabel: "تک افزودنی Single additive",
      categoryLabel: "افرودنی ها Additives",
      categoryIsOwnCell: true,
      comment: "عکس نمونه با تغییرات گذاشته شود(از سایت کپی نشود)",
      technicalReferenceEn: "https://addilex.com/addilex-c-339-ash-free-antioxidant/",
      technicalReferenceFa: "",
    },
    {
      sheetName: "محصولات",
      rowNumber: 252,
      name: "Dispersant",
      rawName: "Dispersant",
      productTypeLabel: "تک افزودنی Single additive",
      categoryLabel: "افرودنی ها Additives",
      categoryIsOwnCell: false,
      comment: "عکس نمونه با تغییرات گذاشته شود(از سایت کپی نشود)",
      technicalReferenceEn: "https://addilex.com/addilex-c-320/",
      technicalReferenceFa: "",
    },
    {
      sheetName: "محصولات",
      rowNumber: 255,
      name: "Ash-less Dispersant",
      rawName: "Ash-less Dispersant",
      productTypeLabel: "تک افزودنی Single additive",
      categoryLabel: "افرودنی ها Additives",
      categoryIsOwnCell: false,
      comment: "عکس نمونه با تغییرات گذاشته شود(از سایت کپی نشود)",
      technicalReferenceEn: "https://addilex.com/addilex-c-321-ashless-dispersant/",
      technicalReferenceFa: "",
    },
    {
      sheetName: "محصولات",
      rowNumber: 258,
      name: "Molybdenum Compound",
      rawName: "Molybdenum Compound",
      productTypeLabel: "تک افزودنی Single additive",
      categoryLabel: "افرودنی ها Additives",
      categoryIsOwnCell: false,
      comment: "قبل این اسم پسوند -N- وجود داره عکس نمونه با تغییرات گذاشته شود(از سایت کپی نشود)",
      technicalReferenceEn: "https://addilex.com/addilex-c-323-n-molybdenum-compound/",
      technicalReferenceFa: "",
    },
    {
      sheetName: "محصولات",
      rowNumber: 261,
      name: "zink-ZDDP",
      rawName: "zink-ZDDP",
      productTypeLabel: "تک افزودنی Single additive",
      categoryLabel: "افرودنی ها Additives",
      categoryIsOwnCell: false,
      comment: "عکس نمونه با تغییرات گذاشته شود(از سایت کپی نشود)",
      technicalReferenceEn: "https://addilex.com/addilex-c-340-zinczddp/",
      technicalReferenceFa: "",
    },
    {
      sheetName: "محصولات",
      rowNumber: 264,
      name: "TB N400 Booster",
      rawName: "TB N400 Booster",
      productTypeLabel: "تک افزودنی Single additive",
      categoryLabel: "افرودنی ها Additives",
      categoryIsOwnCell: false,
      comment: "عکس نمونه با تغییرات گذاشته شود(از سایت کپی نشود)",
      technicalReferenceEn: "https://addilex.com/addilex-c-400-tbn400-booster/",
      technicalReferenceFa: "",
    },
    {
      sheetName: "محصولات",
      rowNumber: 267,
      name: "diesel engine oil additive package",
      rawName: "diesel engine oil additive package",
      productTypeLabel: "بسته ی افرودنی ها Additive package",
      categoryLabel: "افرودنی ها Additives",
      categoryIsOwnCell: false,
      comment: "عکس نمونه با تغییرات گذاشته شود(از سایت کپی نشود)",
      technicalReferenceEn: "https://addilex.com/addilex-d-520-diesel-engine-oil-additive-package/",
      technicalReferenceFa: "",
    },
    {
      sheetName: "محصولات",
      rowNumber: 270,
      name: "CI-4, CH-4, CF-4, CD, SC/CC Engine oil additive",
      rawName: "CI-4, CH-4, CF-4, CD, SC/CC\r\nEngine oil additive",
      productTypeLabel: "بسته ی افرودنی ها Additive package",
      categoryLabel: "افرودنی ها Additives",
      categoryIsOwnCell: false,
      comment: "عکس نمونه با تغییرات گذاشته شود(از سایت کپی نشود)",
      technicalReferenceEn: "https://addilex.com/addilex-d-540-engine-oil-additive/",
      technicalReferenceFa: "",
    },
    {
      sheetName: "محصولات",
      rowNumber: 273,
      name: "SF , SE , SC/CC Engine oil additive",
      rawName: "SF , SE , SC/CC Engine oil additive",
      productTypeLabel: "بسته ی افرودنی ها Additive package",
      categoryLabel: "افرودنی ها Additives",
      categoryIsOwnCell: false,
      comment: "عکس نمونه با تغییرات گذاشته شود(از سایت کپی نشود)",
      technicalReferenceEn: "https://addilex.com/addilex-g-720-engine-oil-additive/",
      technicalReferenceFa: "",
    },
    {
      sheetName: "محصولات",
      rowNumber: 276,
      name: "SL , SJ , SG Engine oil additive package",
      rawName: "SL , SJ , SG Engine oil additive package",
      productTypeLabel: "بسته ی افرودنی ها Additive package",
      categoryLabel: "افرودنی ها Additives",
      categoryIsOwnCell: false,
      comment: "عکس نمونه با تغییرات گذاشته شود(از سایت کپی نشود)",
      technicalReferenceEn: "https://addilex.com/addilex-g-730-engine-oil-additive-package/",
      technicalReferenceFa: "",
    },
    {
      sheetName: "محصولات",
      rowNumber: 279,
      name: "Universal Engine oil additive",
      rawName: "Universal Engine oil additive",
      productTypeLabel: "بسته ی افرودنی ها Additive package",
      categoryLabel: "افرودنی ها Additives",
      categoryIsOwnCell: false,
      comment: "عکس نمونه با تغییرات گذاشته شود(از سایت کپی نشود)",
      technicalReferenceEn: "https://addilex.com/addilex-g-740-universal-engine-oil-additive/",
      technicalReferenceFa: "",
    },
    {
      sheetName: "محصولات",
      rowNumber: 282,
      name: "SN , SM , SL , SJ , SF…SC Engine oil additive",
      rawName: "SN , SM , SL , SJ , SF…SC Engine oil additive",
      productTypeLabel: "بسته ی افرودنی ها Additive package",
      categoryLabel: "افرودنی ها Additives",
      categoryIsOwnCell: false,
      comment: "عکس نمونه با تغییرات گذاشته شود(از سایت کپی نشود)",
      technicalReferenceEn: "https://addilex.com/addilex-g-750-engine-oil-additive/",
      technicalReferenceFa: "",
    },
    {
      sheetName: "محصولات",
      rowNumber: 285,
      name: "Gear oil additive",
      rawName: "Gear oil additive",
      productTypeLabel: "بسته ی افرودنی ها Additive package",
      categoryLabel: "افرودنی ها Additives",
      categoryIsOwnCell: false,
      comment: "عکس نمونه با تغییرات گذاشته شود(از سایت کپی نشود)",
      technicalReferenceEn: "https://addilex.com/addilex-g-388-gear-oil-additive/",
      technicalReferenceFa: "",
    },
    {
      sheetName: "محصولات",
      rowNumber: 288,
      name: "Anti-wear hydraulic oil additive package",
      rawName: "Anti-wear hydraulic oil additive package",
      productTypeLabel: "بسته ی افرودنی ها Additive package",
      categoryLabel: "افرودنی ها Additives",
      categoryIsOwnCell: false,
      comment: "عکس نمونه با تغییرات گذاشته شود(از سایت کپی نشود)",
      technicalReferenceEn:
        "https://addilex.com/addilex-h-515-anti-wear-hydraulic-oil-additive-package/",
      technicalReferenceFa: "",
    },
    {
      sheetName: "محصولات",
      rowNumber: 291,
      name: "Two-stroke motor oil",
      rawName: "Two-stroke motor oil",
      productTypeLabel: "بسته ی افرودنی ها Additive package",
      categoryLabel: "افرودنی ها Additives",
      categoryIsOwnCell: false,
      comment: "عکس نمونه با تغییرات گذاشته شود(از سایت کپی نشود)",
      technicalReferenceEn: "https://addilex.com/addilex-t-961-two-stroke-motor-oil/",
      technicalReferenceFa: "",
    },
    {
      sheetName: "محصولات",
      rowNumber: 294,
      name: "Mineral-Based",
      rawName: "Mineral-Based",
      productTypeLabel: "ضد یخ",
      categoryLabel: "سایر محصولات Others products",
      categoryIsOwnCell: true,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/nv9qe16wtuki34e",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/nv9qe16wtuki34e",
    },
    {
      sheetName: "محصولات",
      rowNumber: 297,
      name: "High-Performance",
      rawName: "High-Performance",
      productTypeLabel: "ضد یخ",
      categoryLabel: "سایر محصولات Others products",
      categoryIsOwnCell: false,
      comment: "فایل TDC گذاشته نشود",
      technicalReferenceEn: "https://kingpowerlub.com/en/products/6xyz_4r76fzu18n",
      technicalReferenceFa: "https://kingpowerlub.com/fa/products/6xyz_4r76fzu18n",
    },
    {
      sheetName: "محصولات",
      rowNumber: 300,
      name: "Grease Based on Calcium",
      rawName: "Grease Based on Calcium",
      productTypeLabel: "گریس",
      categoryLabel: "سایر محصولات Others products",
      categoryIsOwnCell: false,
      comment: "",
      technicalReferenceEn: "کاتالوگ HSB",
      technicalReferenceFa: "کاتالوگ HSB",
    },
  ],
  // The authoritative workbook has no identifier column today. When one is added the
  // parser reads it, and identity stops depending on inference entirely.
  identifierColumn: null,
  declaredSourceRefs: new Map<number, string>(),
};
