-- Product Taxonomy v2, phase 1 — ADR-007. ADDITIVE ONLY.
--
-- Generated by diffing the previous schema state to the edited schema, NOT by
-- re-diffing from empty: 0_init ends with three hand-written partial unique
-- indexes that `prisma migrate diff` cannot reproduce, and this migration must
-- leave all three untouched. It does — nothing below names them.
--
-- No DROP, no data write, and no change to any pre-existing table beyond one
-- nullable column on `products`. `categories`, `products.category_id` and the
-- Category hierarchy are deliberately unchanged.
--
-- Creates the tables and nothing else: no Segment row, no ProductType row and
-- no membership is approved (ADR-007, Deferred Decisions).

-- AlterTable
ALTER TABLE "products" ADD COLUMN     "product_type_id" UUID;

-- CreateTable
CREATE TABLE "segments" (
    "id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "sort_order" INTEGER NOT NULL,

    CONSTRAINT "segments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "product_types" (
    "id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,

    CONSTRAINT "product_types_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "product_segments" (
    "product_id" UUID NOT NULL,
    "segment_id" UUID NOT NULL,

    CONSTRAINT "product_segments_pkey" PRIMARY KEY ("product_id","segment_id")
);

-- CreateTable
CREATE TABLE "segment_product_types" (
    "segment_id" UUID NOT NULL,
    "product_type_id" UUID NOT NULL,
    "sort_order" INTEGER NOT NULL,

    CONSTRAINT "segment_product_types_pkey" PRIMARY KEY ("segment_id","product_type_id")
);

-- CreateIndex
CREATE UNIQUE INDEX "segments_slug_key" ON "segments"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "product_types_slug_key" ON "product_types"("slug");

-- CreateIndex
CREATE INDEX "product_segments_segment_id_idx" ON "product_segments"("segment_id");

-- CreateIndex
CREATE INDEX "segment_product_types_product_type_id_idx" ON "segment_product_types"("product_type_id");

-- CreateIndex
CREATE INDEX "products_product_type_id_idx" ON "products"("product_type_id");

-- AddForeignKey
ALTER TABLE "products" ADD CONSTRAINT "products_product_type_id_fkey" FOREIGN KEY ("product_type_id") REFERENCES "product_types"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_segments" ADD CONSTRAINT "product_segments_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_segments" ADD CONSTRAINT "product_segments_segment_id_fkey" FOREIGN KEY ("segment_id") REFERENCES "segments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "segment_product_types" ADD CONSTRAINT "segment_product_types_segment_id_fkey" FOREIGN KEY ("segment_id") REFERENCES "segments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "segment_product_types" ADD CONSTRAINT "segment_product_types_product_type_id_fkey" FOREIGN KEY ("product_type_id") REFERENCES "product_types"("id") ON DELETE CASCADE ON UPDATE CASCADE;
